Remove redundant declaration of isl_tab_lexmin
Without the removal of this typedef, gcc 4.4 complains about the following:

isl/isl_tab_pip.c:5216: error: redefinition of typedef 'isl_tab_lexmin'
isl/isl_tab.h:268: note: previous declaration of 'isl_tab_lexmin' was here

Signed-off-by: Andreas Kloeckner <inform@tiker.net>
Signed-off-by: Sven Verdoolaege <skimo@kotnet.org>